[fix](doris catalog) FragmentMgr should not cancel virtual doris cluster query (#62135)
RuntimeLogger 2026-03-10 06:52:47,187 INFO (mysql-nio-pool-0|263)
[MultiFragmentsPipelineTask.cancelExecute():112] Fragment has already
been cancelled. Query 125d099a3c8644db-b25df79355a22d7d backend: Backend
[id=1770171528024,
host=[doris-be-0.doris-be-internal.doris.svc.cluster.local](http://doris-be-0.doris-be-internal.doris.svc.cluster.local/),
heartbeatPort=9050, alive=true, lastStartTime=2026-03-10 05:13:37,
process epoch=1773119617506, isDecommissioned=false, tags:
{location=default}], backendStatus:
[lastSuccessReportTabletsTime='2026-03-10 06:52:31',
lastStreamLoadTime=-1, isQueryDisabled=false, isLoadDisabled=false,
currentFragmentNum=0, lastFragmentUpdateTime=1773125544536]
RuntimeLogger 2026-03-10 06:52:47,187 WARN (mysql-nio-pool-0|263)
[StmtExecutor.handleQueryWithRetry():927] retry due to exception errCode
= 2, detailMessage =
([doris-be-0.doris-be-internal.doris.svc.cluster.local](http://doris-be-0.doris-be-internal.doris.svc.cluster.local/))[CANCELLED]Source
frontend is not running or restarted. retried 0 times. is rpc error:
false, is user error: true.
RuntimeLogger 2026-03-10 06:52:47,187 WARN (mysql-nio-pool-0|263)
[StmtExecutor.execute():550] Nereids execute failed. stmt[144,
125d099a3c8644db-b25df79355a22d7d]
org.apache.doris.common.UserException: errCode = 2, detailMessage =
([doris-be-0.doris-be-internal.doris.svc.cluster.local](http://doris-be-0.doris-be-internal.doris.svc.cluster.local/))[CANCELLED]Source
frontend is not running or restarted
        at
org.apache.doris.qe.runtime.QueryProcessor.doGetNext(QueryProcessor.java:166)
        at
org.apache.doris.qe.runtime.QueryProcessor.getNext(QueryProcessor.java:123)
        at
org.apache.doris.qe.NereidsCoordinator.getNext(NereidsCoordinator.java:217)
        at
org.apache.doris.qe.StmtExecutor.executeAndSendResult(StmtExecutor.java:1321)
        at
org.apache.doris.qe.StmtExecutor.handleCacheStmt(StmtExecutor.java:1183)
        at
org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:1254)
        at
org.apache.doris.qe.StmtExecutor.handleQueryWithRetry(StmtExecutor.java:914)
        at
org.apache.doris.qe.StmtExecutor.executeByNereids(StmtExecutor.java:818)
        at
org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:541)
        at
org.apache.doris.qe.StmtExecutor.queryRetry(StmtExecutor.java:500)
        at
org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:485)
        at
org.apache.doris.qe.ConnectProcessor.executeQuery(ConnectProcessor.java:311)
        at
org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:198)
        at
org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:231)
        at
org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:259)
        at
org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:403)
        at
org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52)
        at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)